import { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "hi" | "ta" | "te" | "bn" | "mr" | "gu" | "kn" | "ml" | "pa";

interface LanguageConfig {
  code: Language;
  name: string;
  nativeName: string;
}

export const languages: LanguageConfig[] = [
  { code: "en", name: "English", nativeName: "English" },
  { code: "hi", name: "Hindi", nativeName: "हिन्दी" },
  { code: "ta", name: "Tamil", nativeName: "தமிழ்" },
  { code: "te", name: "Telugu", nativeName: "తెలుగు" },
  { code: "bn", name: "Bengali", nativeName: "বাংলা" },
  { code: "mr", name: "Marathi", nativeName: "मराठी" },
  { code: "gu", name: "Gujarati", nativeName: "ગુજરાતી" },
  { code: "kn", name: "Kannada", nativeName: "ಕನ್ನಡ" },
  { code: "ml", name: "Malayalam", nativeName: "മലയാളം" },
  { code: "pa", name: "Punjabi", nativeName: "ਪੰਜਾਬੀ" },
];

type Translations = {
  [key in Language]: {
    [key: string]: string;
  };
};

export const translations: Translations = {
  en: {
    // Navbar
    home: "Home",
    uploadResume: "Upload Resume",
    careerInsights: "Career Insights",
    aiAdvisor: "AI Advisor",
    configure: "Configure",
    login: "Login",
    signOut: "Sign Out",
    
    // Auth
    loginRequired: "Login Required",
    loginRequiredDesc: "Please login or create an account to access this feature.",
    loginSignUp: "Login / Sign Up",
    welcomeBack: "Welcome Back",
    createAccount: "Create Account",
    signInContinue: "Sign in to continue your career journey",
    startExploring: "Start exploring your career possibilities",
    fullName: "Full Name",
    email: "Email",
    password: "Password",
    signIn: "Sign In",
    dontHaveAccount: "Don't have an account? Sign up",
    alreadyHaveAccount: "Already have an account? Sign in",
    error: "Error",
    fillAllFields: "Please fill in all fields.",
    enterName: "Please enter your name.",
    passwordLength: "Password must be at least 6 characters.",
    invalidCredentials: "Invalid email or password.",
    emailRegistered: "This email is already registered. Please log in.",
    confirmEmail: "Please confirm your email before logging in.",
    genericError: "An error occurred. Please try again.",
    accountCreated: "Account created!",
    startUsing: "You can now start using Career Explorer.",
    loggedIn: "You have successfully logged in.",
    
    // Upload
    analyzeResume: "Analyze My Resume",
    analyzingResume: "Analyzing Resume...",
    uploadYourResume: "Upload Your Resume",
    uploadDesc: "Our AI will analyze your resume and provide personalized career recommendations.",
    dragDrop: "Drag & Drop your resume",
    browseFiles: "Browse Files",
    pasteResume: "Or paste your resume text:",
    pasteResumeDesc: "Paste your complete resume content here...",
    securityNotice: "Your resume data is processed securely and never shared.",
    
    // Chat
    aiCareerAdvisor: "AI Career Advisor",
    askAboutCareers: "Ask about careers, interviews, skills...",
    chatWelcome: "Hello! I'm CareerGuide AI, your personal career advisor. How can I help you today? Feel free to ask about career paths, interview tips, skill development, or salary negotiations.",
    chatError: "I apologize, but I encountered an error. Please try again.",
    
    // Hero
    aiPoweredCareer: "AI-Powered Career Intelligence",
    discoverPerfect: "Discover Your",
    perfectCareer: "Perfect Career",
    pathWithAI: "Path with AI",
    heroDescription: "Upload your resume and unlock personalized career recommendations, job matches with salary insights in INR, and AI-powered guidance to accelerate your professional journey.",
    chatWithAI: "Chat with AI",
    securePrivate: "Secure & Private",
    realTimeInsights: "Real-time Insights",
    personalizedMatches: "Personalized Matches",
    smartResume: "Smart Resume Analysis",
    smartResumeDesc: "AI extracts skills, experience, and projects from your resume automatically",
    jobMatching: "Job Matching",
    jobMatchingDesc: "Get personalized job recommendations with match percentages and salary ranges",
    careerGrowth: "Career Growth Insights",
    careerGrowthDesc: "Discover skill gaps and get actionable improvement suggestions",
    
    // How It Works
    howItWorks: "How It",
    works: "Works",
    howItWorksDesc: "From resume upload to career success — our AI-powered platform guides you every step of the way.",
    uploadResumeStep: "Upload Resume",
    uploadResumeStepDesc: "Upload your resume in PDF or text format. Your data is encrypted and secure.",
    aiAnalysis: "AI Analysis",
    aiAnalysisDesc: "Our AI extracts skills, experience, projects, and creates your professional profile.",
    jobMatchingStep: "Job Matching",
    jobMatchingStepDesc: "Get matched with relevant job roles from top Indian companies with salary ranges.",
    careerInsightsStep: "Career Insights",
    careerInsightsStepDesc: "Receive personalized insights on strengths, weaknesses, and improvement areas.",
    aiAdvisorStep: "AI Advisor",
    aiAdvisorStepDesc: "Chat with our AI career advisor for guidance, interview tips, and more.",
    takeAction: "Take Action",
    takeActionDesc: "Apply to matched jobs with an improved resume and confidence.",
    
    // Footer
    careerExplorer: "Career Explorer",
    footerDesc: "Empowering your career journey with AI-powered insights, personalized recommendations, and secure resume processing. Your future starts here.",
    securityFirst: "Security First",
    endToEndEncryption: "End-to-end encryption",
    privacyProtected: "Privacy protected",
    quickLinks: "Quick Links",
    madeWith: "Made with",
    forCareer: "for your career success",
    allRightsReserved: "All rights reserved.",
    
    // Recommendations
    yourCareer: "Your Career",
    insights: "Insights",
    noResumeYet: "No Resume Analyzed Yet",
    uploadToGetInsights: "Upload your resume to get personalized career insights.",
    strengths: "Strengths",
    areasToImprove: "Areas to Improve",
    suggestedCourses: "Suggested Courses:",
    skills: "Skills",
    jobRecommendations: "Job Recommendations",
    matchScore: "Match Score",
    requiredSkills: "Required Skills:",
    skillsToLearn: "Skills to Learn:",
    resumeImprovementTips: "Resume Improvement Tips",
  },
  hi: {
    // Navbar
    home: "होम",
    uploadResume: "रिज्यूमे अपलोड करें",
    careerInsights: "करियर इनसाइट्स",
    aiAdvisor: "AI सलाहकार",
    configure: "कॉन्फ़िगर",
    login: "लॉग इन",
    signOut: "साइन आउट",
    
    // Auth
    loginRequired: "लॉगिन आवश्यक",
    loginRequiredDesc: "कृपया इस सुविधा का उपयोग करने के लिए लॉगिन करें या खाता बनाएं।",
    loginSignUp: "लॉगिन / साइन अप",
    welcomeBack: "वापसी पर स्वागत है",
    createAccount: "खाता बनाएं",
    signInContinue: "अपनी करियर यात्रा जारी रखने के लिए साइन इन करें",
    startExploring: "अपनी करियर संभावनाओं का पता लगाना शुरू करें",
    fullName: "पूरा नाम",
    email: "ईमेल",
    password: "पासवर्ड",
    signIn: "साइन इन",
    dontHaveAccount: "खाता नहीं है? साइन अप करें",
    alreadyHaveAccount: "पहले से खाता है? साइन इन करें",
    error: "त्रुटि",
    fillAllFields: "कृपया सभी फ़ील्ड भरें।",
    enterName: "कृपया अपना नाम दर्ज करें।",
    passwordLength: "पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।",
    invalidCredentials: "गलत ईमेल या पासवर्ड।",
    emailRegistered: "यह ईमेल पहले से पंजीकृत है। कृपया लॉगिन करें।",
    confirmEmail: "लॉगिन करने से पहले कृपया अपना ईमेल कन्फर्म करें।",
    genericError: "एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    accountCreated: "खाता बनाया गया!",
    startUsing: "अब आप Career Explorer का उपयोग शुरू कर सकते हैं।",
    loggedIn: "आपने सफलतापूर्वक लॉगिन किया।",
    
    // Upload
    analyzeResume: "मेरा रिज्यूमे विश्लेषण करें",
    analyzingResume: "रिज्यूमे का विश्लेषण हो रहा है...",
    uploadYourResume: "अपना रिज्यूमे अपलोड करें",
    uploadDesc: "हमारा AI आपके रिज्यूमे का विश्लेषण करेगा।",
    dragDrop: "अपना रिज्यूमे ड्रैग एंड ड्रॉप करें",
    browseFiles: "फ़ाइलें ब्राउज़ करें",
    pasteResume: "या अपना रिज्यूमे टेक्स्ट पेस्ट करें:",
    pasteResumeDesc: "अपनी पूरी रिज्यूमे सामग्री यहां पेस्ट करें...",
    securityNotice: "आपका रिज्यूमे डेटा सुरक्षित रूप से संसाधित होता है।",
    
    // Chat
    aiCareerAdvisor: "AI करियर सलाहकार",
    askAboutCareers: "करियर, इंटरव्यू, स्किल्स के बारे में पूछें...",
    chatWelcome: "नमस्ते! मैं CareerGuide AI हूं, आपका व्यक्तिगत करियर सलाहकार। आज मैं आपकी कैसे मदद कर सकता हूं?",
    chatError: "मुझे खेद है, लेकिन एक त्रुटि हुई। कृपया पुनः प्रयास करें।",
    
    // Hero
    aiPoweredCareer: "AI-संचालित करियर इंटेलिजेंस",
    discoverPerfect: "अपना खोजें",
    perfectCareer: "परफेक्ट करियर",
    pathWithAI: "AI के साथ पथ",
    heroDescription: "अपना रिज्यूमे अपलोड करें और व्यक्तिगत करियर सिफारिशें, INR में वेतन जानकारी के साथ नौकरी मैच, और अपनी व्यावसायिक यात्रा को तेज करने के लिए AI-संचालित मार्गदर्शन प्राप्त करें।",
    chatWithAI: "AI से चैट करें",
    securePrivate: "सुरक्षित और निजी",
    realTimeInsights: "रीयल-टाइम इनसाइट्स",
    personalizedMatches: "व्यक्तिगत मैच",
    smartResume: "स्मार्ट रिज्यूमे विश्लेषण",
    smartResumeDesc: "AI आपके रिज्यूमे से स्किल्स, अनुभव और प्रोजेक्ट्स स्वचालित रूप से निकालता है",
    jobMatching: "नौकरी मैचिंग",
    jobMatchingDesc: "मैच प्रतिशत और वेतन सीमाओं के साथ व्यक्तिगत नौकरी सिफारिशें प्राप्त करें",
    careerGrowth: "करियर विकास इनसाइट्स",
    careerGrowthDesc: "स्किल गैप्स खोजें और कार्रवाई योग्य सुधार सुझाव प्राप्त करें",
    
    // How It Works
    howItWorks: "यह कैसे",
    works: "काम करता है",
    howItWorksDesc: "रिज्यूमे अपलोड से करियर सफलता तक — हमारा AI-संचालित प्लेटफॉर्म हर कदम पर आपका मार्गदर्शन करता है।",
    uploadResumeStep: "रिज्यूमे अपलोड करें",
    uploadResumeStepDesc: "PDF या टेक्स्ट फॉर्मेट में अपना रिज्यूमे अपलोड करें। आपका डेटा एन्क्रिप्टेड और सुरक्षित है।",
    aiAnalysis: "AI विश्लेषण",
    aiAnalysisDesc: "हमारा AI स्किल्स, अनुभव, प्रोजेक्ट्स निकालता है और आपकी पेशेवर प्रोफ़ाइल बनाता है।",
    jobMatchingStep: "नौकरी मैचिंग",
    jobMatchingStepDesc: "शीर्ष भारतीय कंपनियों से वेतन सीमाओं के साथ प्रासंगिक नौकरी भूमिकाओं से मिलान करें।",
    careerInsightsStep: "करियर इनसाइट्स",
    careerInsightsStepDesc: "ताकत, कमजोरियों और सुधार क्षेत्रों पर व्यक्तिगत अंतर्दृष्टि प्राप्त करें।",
    aiAdvisorStep: "AI सलाहकार",
    aiAdvisorStepDesc: "मार्गदर्शन, इंटरव्यू टिप्स और अधिक के लिए हमारे AI करियर सलाहकार से चैट करें।",
    takeAction: "कार्रवाई करें",
    takeActionDesc: "बेहतर रिज्यूमे और आत्मविश्वास के साथ मिलान नौकरियों पर आवेदन करें।",
    
    // Footer
    careerExplorer: "करियर एक्सप्लोरर",
    footerDesc: "AI-संचालित अंतर्दृष्टि, व्यक्तिगत सिफारिशों और सुरक्षित रिज्यूमे प्रोसेसिंग के साथ आपकी करियर यात्रा को सशक्त बनाना। आपका भविष्य यहां शुरू होता है।",
    securityFirst: "सुरक्षा पहले",
    endToEndEncryption: "एंड-टू-एंड एन्क्रिप्शन",
    privacyProtected: "गोपनीयता सुरक्षित",
    quickLinks: "त्वरित लिंक",
    madeWith: "बनाया गया",
    forCareer: "आपकी करियर सफलता के लिए",
    allRightsReserved: "सर्वाधिकार सुरक्षित।",
    
    // Recommendations
    yourCareer: "आपकी करियर",
    insights: "इनसाइट्स",
    noResumeYet: "अभी कोई रिज्यूमे विश्लेषित नहीं",
    uploadToGetInsights: "व्यक्तिगत करियर अंतर्दृष्टि प्राप्त करने के लिए अपना रिज्यूमे अपलोड करें।",
    strengths: "ताकतें",
    areasToImprove: "सुधार के क्षेत्र",
    suggestedCourses: "सुझाए गए कोर्स:",
    skills: "स्किल्स",
    jobRecommendations: "नौकरी सिफारिशें",
    matchScore: "मैच स्कोर",
    requiredSkills: "आवश्यक स्किल्स:",
    skillsToLearn: "सीखने के लिए स्किल्स:",
    resumeImprovementTips: "रिज्यूमे सुधार टिप्स",
  },
  ta: {
    // Navbar
    home: "முகப்பு",
    uploadResume: "Resume பதிவேற்றம்",
    careerInsights: "தொழில் நுண்ணறிவு",
    aiAdvisor: "AI ஆலோசகர்",
    configure: "அமைப்புகள்",
    login: "உள்நுழைவு",
    signOut: "வெளியேறு",
    
    // Auth
    loginRequired: "உள்நுழைவு தேவை",
    loginRequiredDesc: "இந்த அம்சத்தைப் பயன்படுத்த உள்நுழையவும்.",
    loginSignUp: "உள்நுழைவு / பதிவு",
    welcomeBack: "மீண்டும் வரவேற்கிறோம்",
    createAccount: "கணக்கை உருவாக்கு",
    signInContinue: "உங்கள் தொழில் பயணத்தைத் தொடர உள்நுழையவும்",
    startExploring: "உங்கள் தொழில் வாய்ப்புகளை ஆராயத் தொடங்குங்கள்",
    fullName: "முழு பெயர்",
    email: "மின்னஞ்சல்",
    password: "கடவுச்சொல்",
    signIn: "உள்நுழைக",
    dontHaveAccount: "கணக்கு இல்லையா? பதிவு செய்யுங்கள்",
    alreadyHaveAccount: "ஏற்கனவே கணக்கு உள்ளதா? உள்நுழையுங்கள்",
    error: "பிழை",
    fillAllFields: "அனைத்து புலங்களையும் நிரப்பவும்.",
    enterName: "உங்கள் பெயரை உள்ளிடவும்.",
    passwordLength: "கடவுச்சொல் குறைந்தது 6 எழுத்துக்கள் இருக்க வேண்டும்.",
    invalidCredentials: "தவறான மின்னஞ்சல் அல்லது கடவுச்சொல்.",
    emailRegistered: "இந்த மின்னஞ்சல் ஏற்கனவே பதிவு செய்யப்பட்டுள்ளது.",
    confirmEmail: "உள்நுழைவதற்கு முன் உங்கள் மின்னஞ்சலை உறுதிப்படுத்தவும்.",
    genericError: "ஒரு பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    accountCreated: "கணக்கு உருவாக்கப்பட்டது!",
    startUsing: "இப்போது Career Explorer ஐ பயன்படுத்தத் தொடங்கலாம்.",
    loggedIn: "நீங்கள் வெற்றிகரமாக உள்நுழைந்துள்ளீர்கள்.",
    
    // Upload
    analyzeResume: "என் Resume ஐ பகுப்பாய்வு செய்",
    analyzingResume: "Resume பகுப்பாய்வு செய்யப்படுகிறது...",
    uploadYourResume: "உங்கள் Resume ஐ பதிவேற்றவும்",
    uploadDesc: "எங்கள் AI உங்கள் Resume ஐ பகுப்பாய்வு செய்யும்.",
    dragDrop: "உங்கள் Resume ஐ இழுத்து விடுங்கள்",
    browseFiles: "கோப்புகளை உலாவவும்",
    pasteResume: "அல்லது உங்கள் Resume உரையை ஒட்டவும்:",
    pasteResumeDesc: "உங்கள் முழு Resume உள்ளடக்கத்தை இங்கே ஒட்டவும்...",
    securityNotice: "உங்கள் Resume தரவு பாதுகாப்பாக செயலாக்கப்படுகிறது.",
    
    // Chat
    aiCareerAdvisor: "AI தொழில் ஆலோசகர்",
    askAboutCareers: "தொழில், நேர்காணல் பற்றி கேளுங்கள்...",
    chatWelcome: "வணக்கம்! நான் CareerGuide AI, உங்கள் தனிப்பட்ட தொழில் ஆலோசகர். இன்று நான் உங்களுக்கு எப்படி உதவ முடியும்?",
    chatError: "மன்னிக்கவும், ஒரு பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.",
    
    // Hero
    aiPoweredCareer: "AI-இயக்கப்படும் தொழில் நுண்ணறிவு",
    discoverPerfect: "உங்கள் கண்டுபிடியுங்கள்",
    perfectCareer: "சரியான தொழில்",
    pathWithAI: "AI உடன் பாதை",
    heroDescription: "உங்கள் Resume ஐ பதிவேற்றி தனிப்பயனாக்கப்பட்ட தொழில் பரிந்துரைகள், INR இல் சம்பள தகவல்களுடன் வேலை பொருத்தங்கள் மற்றும் AI-இயக்கப்படும் வழிகாட்டுதலைப் பெறுங்கள்.",
    chatWithAI: "AI உடன் அரட்டை",
    securePrivate: "பாதுகாப்பான & தனிப்பட்ட",
    realTimeInsights: "நிகழ்நேர நுண்ணறிவுகள்",
    personalizedMatches: "தனிப்பயனாக்கப்பட்ட பொருத்தங்கள்",
    smartResume: "ஸ்மார்ட் Resume பகுப்பாய்வு",
    smartResumeDesc: "AI உங்கள் Resume இலிருந்து திறன்கள், அனுபவம் மற்றும் திட்டங்களை தானாக எடுக்கிறது",
    jobMatching: "வேலை பொருத்தம்",
    jobMatchingDesc: "பொருத்த சதவீதங்கள் மற்றும் சம்பள வரம்புகளுடன் தனிப்பயனாக்கப்பட்ட வேலை பரிந்துரைகளைப் பெறுங்கள்",
    careerGrowth: "தொழில் வளர்ச்சி நுண்ணறிவுகள்",
    careerGrowthDesc: "திறன் இடைவெளிகளைக் கண்டறிந்து செயல்படக்கூடிய மேம்பாட்டு பரிந்துரைகளைப் பெறுங்கள்",
    
    // How It Works
    howItWorks: "இது எப்படி",
    works: "வேலை செய்கிறது",
    howItWorksDesc: "Resume பதிவேற்றம் முதல் தொழில் வெற்றி வரை — எங்கள் AI-இயக்கப்படும் தளம் ஒவ்வொரு அடியிலும் உங்களை வழிநடத்துகிறது.",
    uploadResumeStep: "Resume பதிவேற்றம்",
    uploadResumeStepDesc: "PDF அல்லது உரை வடிவத்தில் உங்கள் Resume ஐ பதிவேற்றவும். உங்கள் தரவு குறியாக்கம் செய்யப்பட்டு பாதுகாப்பானது.",
    aiAnalysis: "AI பகுப்பாய்வு",
    aiAnalysisDesc: "எங்கள் AI திறன்கள், அனுபவம், திட்டங்களை எடுத்து உங்கள் தொழில்முறை சுயவிவரத்தை உருவாக்குகிறது.",
    jobMatchingStep: "வேலை பொருத்தம்",
    jobMatchingStepDesc: "சம்பள வரம்புகளுடன் முன்னணி இந்திய நிறுவனங்களிலிருந்து தொடர்புடைய வேலை பங்குகளுடன் பொருந்துங்கள்.",
    careerInsightsStep: "தொழில் நுண்ணறிவுகள்",
    careerInsightsStepDesc: "பலங்கள், பலவீனங்கள் மற்றும் மேம்பாட்டு பகுதிகளில் தனிப்பயனாக்கப்பட்ட நுண்ணறிவுகளைப் பெறுங்கள்.",
    aiAdvisorStep: "AI ஆலோசகர்",
    aiAdvisorStepDesc: "வழிகாட்டுதல், நேர்காணல் குறிப்புகள் மற்றும் பலவற்றிற்கு எங்கள் AI தொழில் ஆலோசகருடன் அரட்டை அடியுங்கள்.",
    takeAction: "நடவடிக்கை எடுங்கள்",
    takeActionDesc: "மேம்படுத்தப்பட்ட Resume மற்றும் நம்பிக்கையுடன் பொருந்திய வேலைகளுக்கு விண்ணப்பிக்கவும்.",
    
    // Footer
    careerExplorer: "தொழில் ஆராய்ச்சியாளர்",
    footerDesc: "AI-இயக்கப்படும் நுண்ணறிவுகள், தனிப்பயனாக்கப்பட்ட பரிந்துரைகள் மற்றும் பாதுகாப்பான Resume செயலாக்கத்துடன் உங்கள் தொழில் பயணத்தை வலுப்படுத்துதல். உங்கள் எதிர்காலம் இங்கே தொடங்குகிறது.",
    securityFirst: "பாதுகாப்பு முதலில்",
    endToEndEncryption: "எண்ட்-டு-எண்ட் குறியாக்கம்",
    privacyProtected: "தனியுரிமை பாதுகாக்கப்பட்டது",
    quickLinks: "விரைவு இணைப்புகள்",
    madeWith: "உருவாக்கப்பட்டது",
    forCareer: "உங்கள் தொழில் வெற்றிக்காக",
    allRightsReserved: "அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    
    // Recommendations
    yourCareer: "உங்கள் தொழில்",
    insights: "நுண்ணறிவுகள்",
    noResumeYet: "இன்னும் Resume பகுப்பாய்வு செய்யப்படவில்லை",
    uploadToGetInsights: "தனிப்பயனாக்கப்பட்ட தொழில் நுண்ணறிவுகளைப் பெற உங்கள் Resume ஐ பதிவேற்றவும்.",
    strengths: "பலங்கள்",
    areasToImprove: "மேம்படுத்த வேண்டிய பகுதிகள்",
    suggestedCourses: "பரிந்துரைக்கப்பட்ட படிப்புகள்:",
    skills: "திறன்கள்",
    jobRecommendations: "வேலை பரிந்துரைகள்",
    matchScore: "பொருத்த மதிப்பெண்",
    requiredSkills: "தேவையான திறன்கள்:",
    skillsToLearn: "கற்க வேண்டிய திறன்கள்:",
    resumeImprovementTips: "Resume மேம்பாட்டு குறிப்புகள்",
  },
  te: {
    // Navbar
    home: "హోమ్",
    uploadResume: "Resume అప్‌లోడ్",
    careerInsights: "కెరీర్ అంతర్దృష్టులు",
    aiAdvisor: "AI సలహాదారు",
    configure: "కాన్ఫిగర్",
    login: "లాగిన్",
    signOut: "సైన్ అవుట్",
    
    // Auth
    loginRequired: "లాగిన్ అవసరం",
    loginRequiredDesc: "ఈ ఫీచర్‌ను యాక్సెస్ చేయడానికి లాగిన్ అవ్వండి.",
    loginSignUp: "లాగిన్ / సైన్ అప్",
    welcomeBack: "తిరిగి స్వాగతం",
    createAccount: "ఖాతాను సృష్టించండి",
    signInContinue: "మీ కెరీర్ ప్రయాణాన్ని కొనసాగించడానికి సైన్ ఇన్ చేయండి",
    startExploring: "మీ కెరీర్ అవకాశాలను అన్వేషించడం ప్రారంభించండి",
    fullName: "పూర్తి పేరు",
    email: "ఇమెయిల్",
    password: "పాస్‌వర్డ్",
    signIn: "సైన్ ఇన్",
    dontHaveAccount: "ఖాతా లేదా? సైన్ అప్ చేయండి",
    alreadyHaveAccount: "ఇప్పటికే ఖాతా ఉందా? సైన్ ఇన్ చేయండి",
    error: "లోపం",
    fillAllFields: "దయచేసి అన్ని ఫీల్డ్‌లను పూరించండి.",
    enterName: "దయచేసి మీ పేరు నమోదు చేయండి.",
    passwordLength: "పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.",
    invalidCredentials: "చెల్లని ఇమెయిల్ లేదా పాస్‌వర్డ్.",
    emailRegistered: "ఈ ఇమెయిల్ ఇప్పటికే నమోదు చేయబడింది.",
    confirmEmail: "లాగిన్ చేయడానికి ముందు మీ ఇమెయిల్‌ను నిర్ధారించండి.",
    genericError: "లోపం సంభవించింది. మళ్ళీ ప్రయత్నించండి.",
    accountCreated: "ఖాతా సృష్టించబడింది!",
    startUsing: "ఇప్పుడు మీరు Career Explorer ను ఉపయోగించడం ప్రారంభించవచ్చు.",
    loggedIn: "మీరు విజయవంతంగా లాగిన్ అయ్యారు.",
    
    // Upload
    analyzeResume: "నా Resume ను విశ్లేషించండి",
    analyzingResume: "Resume విశ్లేషించబడుతోంది...",
    uploadYourResume: "మీ Resume ను అప్‌లోడ్ చేయండి",
    uploadDesc: "మా AI మీ Resume ను విశ్లేషిస్తుంది.",
    dragDrop: "మీ Resume ను డ్రాగ్ & డ్రాప్ చేయండి",
    browseFiles: "ఫైల్‌లను బ్రౌజ్ చేయండి",
    pasteResume: "లేదా మీ Resume టెక్స్ట్‌ను పేస్ట్ చేయండి:",
    pasteResumeDesc: "మీ పూర్తి Resume కంటెంట్‌ను ఇక్కడ పేస్ట్ చేయండి...",
    securityNotice: "మీ Resume డేటా సురక్షితంగా ప్రాసెస్ చేయబడుతుంది.",
    
    // Chat
    aiCareerAdvisor: "AI కెరీర్ సలహాదారు",
    askAboutCareers: "కెరీర్లు, ఇంటర్వ్యూల గురించి అడగండి...",
    chatWelcome: "హలో! నేను CareerGuide AI, మీ వ్యక్తిగత కెరీర్ సలహాదారు. ఈ రోజు నేను మీకు ఎలా సహాయం చేయగలను?",
    chatError: "క్షమించండి, లోపం సంభవించింది. మళ్ళీ ప్రయత్నించండి.",
    
    // Hero
    aiPoweredCareer: "AI-ఆధారిత కెరీర్ ఇంటెలిజెన్స్",
    discoverPerfect: "మీ కనుగొనండి",
    perfectCareer: "పర్ఫెక్ట్ కెరీర్",
    pathWithAI: "AI తో మార్గం",
    heroDescription: "మీ Resume ను అప్‌లోడ్ చేసి వ్యక్తిగతీకరించిన కెరీర్ సిఫారసులు, INR లో జీతం సమాచారంతో ఉద్యోగ సరిపోలికలు మరియు AI-ఆధారిత మార్గదర్శకత్వాన్ని పొందండి.",
    chatWithAI: "AI తో చాట్ చేయండి",
    securePrivate: "సురక్షితం & ప్రైవేట్",
    realTimeInsights: "రియల్-టైమ్ అంతర్దృష్టులు",
    personalizedMatches: "వ్యక్తిగతీకరించిన సరిపోలికలు",
    smartResume: "స్మార్ట్ Resume విశ్లేషణ",
    smartResumeDesc: "AI మీ Resume నుండి నైపుణ్యాలు, అనుభవం మరియు ప్రాజెక్ట్‌లను స్వయంచాలకంగా సంగ్రహిస్తుంది",
    jobMatching: "ఉద్యోగ సరిపోలిక",
    jobMatchingDesc: "సరిపోలిక శాతాలు మరియు జీతం పరిధులతో వ్యక్తిగతీకరించిన ఉద్యోగ సిఫారసులను పొందండి",
    careerGrowth: "కెరీర్ వృద్ధి అంతర్దృష్టులు",
    careerGrowthDesc: "నైపుణ్యం అంతరాలను కనుగొని చర్యాత్మక మెరుగుదల సూచనలను పొందండి",
    
    // How It Works
    howItWorks: "ఇది ఎలా",
    works: "పని చేస్తుంది",
    howItWorksDesc: "Resume అప్‌లోడ్ నుండి కెరీర్ విజయం వరకు — మా AI-ఆధారిత ప్లాట్‌ఫారమ్ ప్రతి అడుగులో మీకు మార్గదర్శకత్వం చేస్తుంది.",
    uploadResumeStep: "Resume అప్‌లోడ్",
    uploadResumeStepDesc: "PDF లేదా టెక్స్ట్ ఫార్మాట్‌లో మీ Resume ను అప్‌లోడ్ చేయండి. మీ డేటా ఎన్‌క్రిప్ట్ చేయబడి సురక్షితంగా ఉంటుంది.",
    aiAnalysis: "AI విశ్లేషణ",
    aiAnalysisDesc: "మా AI నైపుణ్యాలు, అనుభవం, ప్రాజెక్ట్‌లను సంగ్రహించి మీ వృత్తిపరమైన ప్రొఫైల్‌ను సృష్టిస్తుంది.",
    jobMatchingStep: "ఉద్యోగ సరిపోలిక",
    jobMatchingStepDesc: "జీతం పరిధులతో అగ్ర భారతీయ కంపెనీల నుండి సంబంధిత ఉద్యోగ పాత్రలతో సరిపోలండి.",
    careerInsightsStep: "కెరీర్ అంతర్దృష్టులు",
    careerInsightsStepDesc: "బలాలు, బలహీనతలు మరియు మెరుగుదల ప్రాంతాలపై వ్యక్తిగతీకరించిన అంతర్దృష్టులను పొందండి.",
    aiAdvisorStep: "AI సలహాదారు",
    aiAdvisorStepDesc: "మార్గదర్శకత్వం, ఇంటర్వ్యూ చిట్కాలు మరియు మరిన్నింటి కోసం మా AI కెరీర్ సలహాదారుతో చాట్ చేయండి.",
    takeAction: "చర్య తీసుకోండి",
    takeActionDesc: "మెరుగైన Resume మరియు నమ్మకంతో సరిపోలిన ఉద్యోగాలకు దరఖాస్తు చేయండి.",
    
    // Footer
    careerExplorer: "కెరీర్ ఎక్స్‌ప్లోరర్",
    footerDesc: "AI-ఆధారిత అంతర్దృష్టులు, వ్యక్తిగతీకరించిన సిఫారసులు మరియు సురక్షిత Resume ప్రాసెసింగ్‌తో మీ కెరీర్ ప్రయాణాన్ని శక్తివంతం చేయడం. మీ భవిష్యత్తు ఇక్కడ ప్రారంభమవుతుంది.",
    securityFirst: "భద్రత మొదట",
    endToEndEncryption: "ఎండ్-టు-ఎండ్ ఎన్‌క్రిప్షన్",
    privacyProtected: "గోప్యత రక్షించబడింది",
    quickLinks: "త్వరిత లింకులు",
    madeWith: "తయారు చేయబడింది",
    forCareer: "మీ కెరీర్ విజయం కోసం",
    allRightsReserved: "అన్ని హక్కులు రిజర్వ్ చేయబడ్డాయి.",
    
    // Recommendations
    yourCareer: "మీ కెరీర్",
    insights: "అంతర్దృష్టులు",
    noResumeYet: "ఇంకా Resume విశ్లేషించబడలేదు",
    uploadToGetInsights: "వ్యక్తిగతీకరించిన కెరీర్ అంతర్దృష్టులను పొందడానికి మీ Resume ను అప్‌లోడ్ చేయండి.",
    strengths: "బలాలు",
    areasToImprove: "మెరుగుపరచవలసిన ప్రాంతాలు",
    suggestedCourses: "సూచించిన కోర్సులు:",
    skills: "నైపుణ్యాలు",
    jobRecommendations: "ఉద్యోగ సిఫారసులు",
    matchScore: "సరిపోలిక స్కోర్",
    requiredSkills: "అవసరమైన నైపుణ్యాలు:",
    skillsToLearn: "నేర్చుకోవలసిన నైపుణ్యాలు:",
    resumeImprovementTips: "Resume మెరుగుదల చిట్కాలు",
  },
  bn: {
    home: "হোম",
    uploadResume: "রিজিউম আপলোড",
    careerInsights: "ক্যারিয়ার ইনসাইটস",
    aiAdvisor: "AI উপদেষ্টা",
    configure: "কনফিগার",
    login: "লগইন",
    signOut: "সাইন আউট",
    loginRequired: "লগইন প্রয়োজন",
    loginRequiredDesc: "এই বৈশিষ্ট্য অ্যাক্সেস করতে লগইন করুন।",
    loginSignUp: "লগইন / সাইন আপ",
    analyzeResume: "আমার রিজিউম বিশ্লেষণ করুন",
    analyzingResume: "রিজিউম বিশ্লেষণ হচ্ছে...",
    uploadYourResume: "আপনার রিজিউম আপলোড করুন",
    uploadDesc: "আমাদের AI আপনার রিজিউম বিশ্লেষণ করবে।",
    dragDrop: "আপনার রিজিউম টেনে আনুন",
    browseFiles: "ফাইল ব্রাউজ করুন",
    pasteResume: "অথবা আপনার রিজিউম টেক্সট পেস্ট করুন:",
    pasteResumeDesc: "আপনার সম্পূর্ণ রিজিউম এখানে পেস্ট করুন...",
    securityNotice: "আপনার রিজিউম ডেটা নিরাপদে প্রক্রিয়া করা হয়।",
    aiCareerAdvisor: "AI ক্যারিয়ার উপদেষ্টা",
    askAboutCareers: "ক্যারিয়ার, ইন্টারভিউ সম্পর্কে জিজ্ঞাসা করুন...",
    welcomeBack: "স্বাগতম",
    createAccount: "অ্যাকাউন্ট তৈরি করুন",
    signInContinue: "আপনার ক্যারিয়ার যাত্রা চালিয়ে যেতে সাইন ইন করুন",
    startExploring: "আপনার ক্যারিয়ার সম্ভাবনা অন্বেষণ শুরু করুন",
    fullName: "পুরো নাম",
    email: "ইমেল",
    password: "পাসওয়ার্ড",
    signIn: "সাইন ইন",
    dontHaveAccount: "অ্যাকাউন্ট নেই? সাইন আপ করুন",
    alreadyHaveAccount: "ইতিমধ্যে অ্যাকাউন্ট আছে? সাইন ইন করুন",
    error: "ত্রুটি",
    fillAllFields: "সব ফিল্ড পূরণ করুন।",
    enterName: "আপনার নাম লিখুন।",
    passwordLength: "পাসওয়ার্ড কমপক্ষে ৬ অক্ষর হতে হবে।",
    invalidCredentials: "ভুল ইমেল বা পাসওয়ার্ড।",
    emailRegistered: "এই ইমেল ইতিমধ্যে নিবন্ধিত।",
    confirmEmail: "লগইন করার আগে আপনার ইমেল নিশ্চিত করুন।",
    genericError: "একটি ত্রুটি হয়েছে। আবার চেষ্টা করুন।",
    accountCreated: "অ্যাকাউন্ট তৈরি হয়েছে!",
    startUsing: "এখন আপনি Career Explorer ব্যবহার শুরু করতে পারেন।",
    loggedIn: "আপনি সফলভাবে লগইন করেছেন।",
    chatWelcome: "হ্যালো! আমি CareerGuide AI, আপনার ব্যক্তিগত ক্যারিয়ার উপদেষ্টা।",
    chatError: "দুঃখিত, একটি ত্রুটি হয়েছে। আবার চেষ্টা করুন।",
    aiPoweredCareer: "AI-চালিত ক্যারিয়ার ইন্টেলিজেন্স",
    discoverPerfect: "আপনার খুঁজুন",
    perfectCareer: "নিখুঁত ক্যারিয়ার",
    pathWithAI: "AI সহ পথ",
    heroDescription: "আপনার রিজিউম আপলোড করুন এবং ব্যক্তিগতকৃত ক্যারিয়ার সুপারিশ, INR তে বেতন তথ্য সহ চাকরি ম্যাচ এবং AI-চালিত গাইডেন্স পান।",
    chatWithAI: "AI এর সাথে চ্যাট করুন",
    securePrivate: "নিরাপদ ও ব্যক্তিগত",
    realTimeInsights: "রিয়েল-টাইম ইনসাইটস",
    personalizedMatches: "ব্যক্তিগতকৃত ম্যাচ",
    smartResume: "স্মার্ট রিজিউম বিশ্লেষণ",
    smartResumeDesc: "AI আপনার রিজিউম থেকে স্বয়ংক্রিয়ভাবে দক্ষতা, অভিজ্ঞতা এবং প্রকল্প বের করে",
    jobMatching: "চাকরি ম্যাচিং",
    jobMatchingDesc: "ম্যাচ শতাংশ এবং বেতন পরিসীমা সহ ব্যক্তিগতকৃত চাকরি সুপারিশ পান",
    careerGrowth: "ক্যারিয়ার গ্রোথ ইনসাইটস",
    careerGrowthDesc: "দক্ষতার ফাঁক খুঁজুন এবং কার্যকর উন্নতি পরামর্শ পান",
    howItWorks: "এটা কিভাবে",
    works: "কাজ করে",
    howItWorksDesc: "রিজিউম আপলোড থেকে ক্যারিয়ার সাফল্য পর্যন্ত — আমাদের AI-চালিত প্ল্যাটফর্ম প্রতিটি পদক্ষেপে আপনাকে গাইড করে।",
    uploadResumeStep: "রিজিউম আপলোড",
    uploadResumeStepDesc: "PDF বা টেক্সট ফরম্যাটে আপনার রিজিউম আপলোড করুন।",
    aiAnalysis: "AI বিশ্লেষণ",
    aiAnalysisDesc: "আমাদের AI দক্ষতা, অভিজ্ঞতা, প্রকল্প বের করে আপনার পেশাদার প্রোফাইল তৈরি করে।",
    jobMatchingStep: "চাকরি ম্যাচিং",
    jobMatchingStepDesc: "বেতন পরিসীমা সহ শীর্ষ ভারতীয় কোম্পানি থেকে প্রাসঙ্গিক চাকরির ভূমিকার সাথে ম্যাচ করুন।",
    careerInsightsStep: "ক্যারিয়ার ইনসাইটস",
    careerInsightsStepDesc: "শক্তি, দুর্বলতা এবং উন্নতির ক্ষেত্রে ব্যক্তিগতকৃত অন্তর্দৃষ্টি পান।",
    aiAdvisorStep: "AI উপদেষ্টা",
    aiAdvisorStepDesc: "গাইডেন্স, ইন্টারভিউ টিপস এবং আরও অনেক কিছুর জন্য আমাদের AI ক্যারিয়ার উপদেষ্টার সাথে চ্যাট করুন।",
    takeAction: "পদক্ষেপ নিন",
    takeActionDesc: "উন্নত রিজিউম এবং আত্মবিশ্বাসের সাথে ম্যাচ করা চাকরিতে আবেদন করুন।",
    careerExplorer: "ক্যারিয়ার এক্সপ্লোরার",
    footerDesc: "AI-চালিত অন্তর্দৃষ্টি, ব্যক্তিগতকৃত সুপারিশ এবং নিরাপদ রিজিউম প্রসেসিং দিয়ে আপনার ক্যারিয়ার যাত্রাকে শক্তিশালী করা।",
    securityFirst: "নিরাপত্তা প্রথম",
    endToEndEncryption: "এন্ড-টু-এন্ড এনক্রিপশন",
    privacyProtected: "গোপনীয়তা সুরক্ষিত",
    quickLinks: "দ্রুত লিঙ্ক",
    madeWith: "তৈরি করা হয়েছে",
    forCareer: "আপনার ক্যারিয়ার সাফল্যের জন্য",
    allRightsReserved: "সমস্ত অধিকার সংরক্ষিত।",
    yourCareer: "আপনার ক্যারিয়ার",
    insights: "ইনসাইটস",
    noResumeYet: "এখনও কোনো রিজিউম বিশ্লেষণ করা হয়নি",
    uploadToGetInsights: "ব্যক্তিগতকৃত ক্যারিয়ার অন্তর্দৃষ্টি পেতে আপনার রিজিউম আপলোড করুন।",
    strengths: "শক্তি",
    areasToImprove: "উন্নতির ক্ষেত্র",
    suggestedCourses: "প্রস্তাবিত কোর্স:",
    skills: "দক্ষতা",
    jobRecommendations: "চাকরি সুপারিশ",
    matchScore: "ম্যাচ স্কোর",
    requiredSkills: "প্রয়োজনীয় দক্ষতা:",
    skillsToLearn: "শেখার দক্ষতা:",
    resumeImprovementTips: "রিজিউম উন্নতি টিপস",
  },
  mr: {
    home: "होम",
    uploadResume: "रेझ्युमे अपलोड करा",
    careerInsights: "करिअर इनसाइट्स",
    aiAdvisor: "AI सल्लागार",
    configure: "कॉन्फिगर",
    login: "लॉगिन",
    signOut: "साइन आउट",
    loginRequired: "लॉगिन आवश्यक",
    loginRequiredDesc: "या वैशिष्ट्यात प्रवेश करण्यासाठी लॉगिन करा.",
    loginSignUp: "लॉगिन / साइन अप",
    analyzeResume: "माझा रेझ्युमे विश्लेषण करा",
    analyzingResume: "रेझ्युमे विश्लेषण होत आहे...",
    uploadYourResume: "तुमचा रेझ्युमे अपलोड करा",
    uploadDesc: "आमचा AI तुमचा रेझ्युमे विश्लेषण करेल.",
    dragDrop: "तुमचा रेझ्युमे ड्रॅग आणि ड्रॉप करा",
    browseFiles: "फाइल्स ब्राउझ करा",
    pasteResume: "किंवा तुमचा रेझ्युमे टेक्स्ट पेस्ट करा:",
    pasteResumeDesc: "तुमची संपूर्ण रेझ्युमे सामग्री येथे पेस्ट करा...",
    securityNotice: "तुमचा रेझ्युमे डेटा सुरक्षितपणे प्रक्रिया केला जातो.",
    aiCareerAdvisor: "AI करिअर सल्लागार",
    askAboutCareers: "करिअर, मुलाखती बद्दल विचारा...",
    welcomeBack: "पुन्हा स्वागत आहे",
    createAccount: "खाते तयार करा",
    signInContinue: "तुमचा करिअर प्रवास सुरू ठेवण्यासाठी साइन इन करा",
    startExploring: "तुमच्या करिअर शक्यता शोधणे सुरू करा",
    fullName: "पूर्ण नाव",
    email: "ईमेल",
    password: "पासवर्ड",
    signIn: "साइन इन",
    dontHaveAccount: "खाते नाही? साइन अप करा",
    alreadyHaveAccount: "आधीच खाते आहे? साइन इन करा",
    error: "त्रुटी",
    fillAllFields: "कृपया सर्व फील्ड भरा.",
    enterName: "कृपया तुमचे नाव प्रविष्ट करा.",
    passwordLength: "पासवर्ड किमान 6 वर्ण असणे आवश्यक आहे.",
    invalidCredentials: "अवैध ईमेल किंवा पासवर्ड.",
    emailRegistered: "हा ईमेल आधीच नोंदणीकृत आहे.",
    confirmEmail: "लॉगिन करण्यापूर्वी तुमचा ईमेल पुष्टी करा.",
    genericError: "एक त्रुटी आली. पुन्हा प्रयत्न करा.",
    accountCreated: "खाते तयार झाले!",
    startUsing: "आता तुम्ही Career Explorer वापरणे सुरू करू शकता.",
    loggedIn: "तुम्ही यशस्वीरित्या लॉगिन केले.",
    chatWelcome: "नमस्कार! मी CareerGuide AI, तुमचा वैयक्तिक करिअर सल्लागार.",
    chatError: "क्षमस्व, एक त्रुटी आली. पुन्हा प्रयत्न करा.",
    aiPoweredCareer: "AI-चालित करिअर इंटेलिजन्स",
    discoverPerfect: "तुमचा शोधा",
    perfectCareer: "परफेक्ट करिअर",
    pathWithAI: "AI सह मार्ग",
    heroDescription: "तुमचा रेझ्युमे अपलोड करा आणि वैयक्तिकृत करिअर शिफारसी, INR मध्ये पगार माहितीसह नोकरी जुळण्या आणि AI-चालित मार्गदर्शन मिळवा.",
    chatWithAI: "AI शी चॅट करा",
    securePrivate: "सुरक्षित आणि खाजगी",
    realTimeInsights: "रिअल-टाइम इनसाइट्स",
    personalizedMatches: "वैयक्तिकृत जुळण्या",
    smartResume: "स्मार्ट रेझ्युमे विश्लेषण",
    smartResumeDesc: "AI तुमच्या रेझ्युमेमधून कौशल्ये, अनुभव आणि प्रकल्प स्वयंचलितपणे काढतो",
    jobMatching: "नोकरी जुळवणी",
    jobMatchingDesc: "जुळणी टक्केवारी आणि पगार श्रेणींसह वैयक्तिकृत नोकरी शिफारसी मिळवा",
    careerGrowth: "करिअर वाढ इनसाइट्स",
    careerGrowthDesc: "कौशल्य अंतर शोधा आणि कृती करण्यायोग्य सुधारणा सूचना मिळवा",
    howItWorks: "हे कसे",
    works: "काम करते",
    howItWorksDesc: "रेझ्युमे अपलोडपासून करिअर यशापर्यंत — आमचे AI-चालित प्लॅटफॉर्म प्रत्येक पावलावर तुम्हाला मार्गदर्शन करते.",
    uploadResumeStep: "रेझ्युमे अपलोड करा",
    uploadResumeStepDesc: "PDF किंवा टेक्स्ट फॉरमॅटमध्ये तुमचा रेझ्युमे अपलोड करा.",
    aiAnalysis: "AI विश्लेषण",
    aiAnalysisDesc: "आमचा AI कौशल्ये, अनुभव, प्रकल्प काढतो आणि तुमची व्यावसायिक प्रोफाइल तयार करतो.",
    jobMatchingStep: "नोकरी जुळवणी",
    jobMatchingStepDesc: "पगार श्रेणींसह अग्रगण्य भारतीय कंपन्यांमधून संबंधित नोकरी भूमिकांशी जुळवा.",
    careerInsightsStep: "करिअर इनसाइट्स",
    careerInsightsStepDesc: "सामर्थ्य, कमकुवतता आणि सुधारणा क्षेत्रांवर वैयक्तिकृत अंतर्दृष्टी मिळवा.",
    aiAdvisorStep: "AI सल्लागार",
    aiAdvisorStepDesc: "मार्गदर्शन, मुलाखत टिप्स आणि अधिकसाठी आमच्या AI करिअर सल्लागाराशी चॅट करा.",
    takeAction: "कृती करा",
    takeActionDesc: "सुधारित रेझ्युमे आणि आत्मविश्वासाने जुळलेल्या नोकऱ्यांवर अर्ज करा.",
    careerExplorer: "करिअर एक्सप्लोरर",
    footerDesc: "AI-चालित अंतर्दृष्टी, वैयक्तिकृत शिफारसी आणि सुरक्षित रेझ्युमे प्रक्रियेसह तुमचा करिअर प्रवास सशक्त करणे.",
    securityFirst: "सुरक्षितता प्रथम",
    endToEndEncryption: "एंड-टू-एंड एन्क्रिप्शन",
    privacyProtected: "गोपनीयता संरक्षित",
    quickLinks: "जलद दुवे",
    madeWith: "बनवले",
    forCareer: "तुमच्या करिअर यशासाठी",
    allRightsReserved: "सर्व हक्क राखीव.",
    yourCareer: "तुमचा करिअर",
    insights: "इनसाइट्स",
    noResumeYet: "अजून रेझ्युमे विश्लेषित नाही",
    uploadToGetInsights: "वैयक्तिकृत करिअर अंतर्दृष्टी मिळवण्यासाठी तुमचा रेझ्युमे अपलोड करा.",
    strengths: "सामर्थ्य",
    areasToImprove: "सुधारण्याचे क्षेत्र",
    suggestedCourses: "सुचविलेले कोर्सेस:",
    skills: "कौशल्ये",
    jobRecommendations: "नोकरी शिफारसी",
    matchScore: "जुळणी स्कोर",
    requiredSkills: "आवश्यक कौशल्ये:",
    skillsToLearn: "शिकण्याची कौशल्ये:",
    resumeImprovementTips: "रेझ्युमे सुधारणा टिप्स",
  },
  gu: {
    home: "હોમ",
    uploadResume: "રિઝ્યુમે અપલોડ કરો",
    careerInsights: "કારકિર્દી આંતરદૃષ્ટિ",
    aiAdvisor: "AI સલાહકાર",
    configure: "કોન્ફિગર",
    login: "લોગિન",
    signOut: "સાઇન આઉટ",
    loginRequired: "લોગિન જરૂરી",
    loginRequiredDesc: "આ સુવિધા ઍક્સેસ કરવા લોગિન કરો.",
    loginSignUp: "લોગિન / સાઇન અપ",
    analyzeResume: "મારું રિઝ્યુમે વિશ્લેષણ કરો",
    analyzingResume: "રિઝ્યુમે વિશ્લેષણ થઈ રહ્યું છે...",
    uploadYourResume: "તમારું રિઝ્યુમે અપલોડ કરો",
    uploadDesc: "અમારું AI તમારા રિઝ્યુમેનું વિશ્લેષણ કરશે.",
    dragDrop: "તમારું રિઝ્યુમે ડ્રેગ અને ડ્રોપ કરો",
    browseFiles: "ફાઇલ્સ બ્રાઉઝ કરો",
    pasteResume: "અથવા તમારું રિઝ્યુમે ટેક્સ્ટ પેસ્ટ કરો:",
    pasteResumeDesc: "તમારી સંપૂર્ણ રિઝ્યુમે સામગ્રી અહીં પેસ્ટ કરો...",
    securityNotice: "તમારા રિઝ્યુમે ડેટા સુરક્ષિત રીતે પ્રક્રિયા થાય છે.",
    aiCareerAdvisor: "AI કારકિર્દી સલાહકાર",
    askAboutCareers: "કારકિર્દી, ઇન્ટરવ્યૂ વિશે પૂછો...",
    welcomeBack: "પાછા આવ્યા તે સારું",
    createAccount: "ખાતું બનાવો",
    signInContinue: "તમારી કારકિર્દી યાત્રા ચાલુ રાખવા સાઇન ઇન કરો",
    startExploring: "તમારી કારકિર્દી શક્યતાઓ શોધવાનું શરૂ કરો",
    fullName: "પૂરું નામ",
    email: "ઇમેઇલ",
    password: "પાસવર્ડ",
    signIn: "સાઇન ઇન",
    dontHaveAccount: "ખાતું નથી? સાઇન અપ કરો",
    alreadyHaveAccount: "પહેલેથી ખાતું છે? સાઇન ઇન કરો",
    error: "ભૂલ",
    fillAllFields: "કૃપા કરી બધા ફીલ્ડ ભરો.",
    enterName: "કૃપા કરી તમારું નામ દાખલ કરો.",
    passwordLength: "પાસવર્ડ ઓછામાં ઓછા 6 અક્ષરો હોવા જોઈએ.",
    invalidCredentials: "અમાન્ય ઇમેઇલ અથવા પાસવર્ડ.",
    emailRegistered: "આ ઇમેઇલ પહેલેથી નોંધાયેલ છે.",
    confirmEmail: "લોગિન કરતા પહેલા તમારા ઇમેઇલની પુષ્ટિ કરો.",
    genericError: "એક ભૂલ થઈ. ફરી પ્રયાસ કરો.",
    accountCreated: "ખાતું બનાવ્યું!",
    startUsing: "હવે તમે Career Explorer નો ઉપયોગ શરૂ કરી શકો છો.",
    loggedIn: "તમે સફળતાપૂર્વક લોગિન થયા.",
    chatWelcome: "નમસ્તે! હું CareerGuide AI છું, તમારા વ્યક્તિગત કારકિર્દી સલાહકાર.",
    chatError: "માફ કરશો, એક ભૂલ થઈ. ફરી પ્રયાસ કરો.",
    aiPoweredCareer: "AI-સંચાલિત કારકિર્દી ઇન્ટેલિજન્સ",
    discoverPerfect: "તમારું શોધો",
    perfectCareer: "પરફેક્ટ કારકિર્દી",
    pathWithAI: "AI સાથે માર્ગ",
    heroDescription: "તમારું રિઝ્યુમે અપલોડ કરો અને વ્યક્તિગત કારકિર્દી ભલામણો, INR માં પગાર માહિતી સાથે નોકરી મેચ અને AI-સંચાલિત માર્ગદર્શન મેળવો.",
    chatWithAI: "AI સાથે ચેટ કરો",
    securePrivate: "સુરક્ષિત અને ખાનગી",
    realTimeInsights: "રિયલ-ટાઇમ આંતરદૃષ્ટિ",
    personalizedMatches: "વ્યક્તિગત મેચ",
    smartResume: "સ્માર્ટ રિઝ્યુમે વિશ્લેષણ",
    smartResumeDesc: "AI તમારા રિઝ્યુમેમાંથી કૌશલ્યો, અનુભવ અને પ્રોજેક્ટ્સ આપોઆપ કાઢે છે",
    jobMatching: "નોકરી મેચિંગ",
    jobMatchingDesc: "મેચ ટકાવારી અને પગાર રેન્જ સાથે વ્યક્તિગત નોકરી ભલામણો મેળવો",
    careerGrowth: "કારકિર્દી વૃદ્ધિ આંતરદૃષ્ટિ",
    careerGrowthDesc: "કૌશલ્ય ગેપ શોધો અને ક્રિયાત્મક સુધારણા સૂચનો મેળવો",
    howItWorks: "આ કેવી રીતે",
    works: "કામ કરે છે",
    howItWorksDesc: "રિઝ્યુમે અપલોડથી કારકિર્દી સફળતા સુધી — અમારું AI-સંચાલિત પ્લેટફોર્મ દરેક પગલે તમને માર્ગદર્શન આપે છે.",
    uploadResumeStep: "રિઝ્યુમે અપલોડ કરો",
    uploadResumeStepDesc: "PDF અથવા ટેક્સ્ટ ફોર્મેટમાં તમારું રિઝ્યુમે અપલોડ કરો.",
    aiAnalysis: "AI વિશ્લેષણ",
    aiAnalysisDesc: "અમારું AI કૌશલ્યો, અનુભવ, પ્રોજેક્ટ્સ કાઢે છે અને તમારી વ્યાવસાયિક પ્રોફાઇલ બનાવે છે.",
    jobMatchingStep: "નોકરી મેચિંગ",
    jobMatchingStepDesc: "પગાર રેન્જ સાથે ટોચની ભારતીય કંપનીઓમાંથી સંબંધિત નોકરી ભૂમિકાઓ સાથે મેચ કરો.",
    careerInsightsStep: "કારકિર્દી આંતરદૃષ્ટિ",
    careerInsightsStepDesc: "શક્તિઓ, નબળાઈઓ અને સુધારણા ક્ષેત્રો પર વ્યક્તિગત આંતરદૃષ્ટિ મેળવો.",
    aiAdvisorStep: "AI સલાહકાર",
    aiAdvisorStepDesc: "માર્ગદર્શન, ઇન્ટરવ્યૂ ટિપ્સ અને વધુ માટે અમારા AI કારકિર્દી સલાહકાર સાથે ચેટ કરો.",
    takeAction: "પગલાં લો",
    takeActionDesc: "સુધારેલા રિઝ્યુમે અને આત્મવિશ્વાસ સાથે મેચ થયેલી નોકરીઓ માટે અરજી કરો.",
    careerExplorer: "કારકિર્દી એક્સપ્લોરર",
    footerDesc: "AI-સંચાલિત આંતરદૃષ્ટિ, વ્યક્તિગત ભલામણો અને સુરક્ષિત રિઝ્યુમે પ્રોસેસિંગ સાથે તમારી કારકિર્દી યાત્રાને સશક્ત બનાવવી.",
    securityFirst: "સુરક્ષા પ્રથમ",
    endToEndEncryption: "એન્ડ-ટુ-એન્ડ એન્ક્રિપ્શન",
    privacyProtected: "ગોપનીયતા સુરક્ષિત",
    quickLinks: "ઝડપી લિંક્સ",
    madeWith: "બનાવેલું",
    forCareer: "તમારી કારકિર્દી સફળતા માટે",
    allRightsReserved: "બધા હક્કો અનામત.",
    yourCareer: "તમારી કારકિર્દી",
    insights: "આંતરદૃષ્ટિ",
    noResumeYet: "હજુ સુધી કોઈ રિઝ્યુમે વિશ્લેષિત નથી",
    uploadToGetInsights: "વ્યક્તિગત કારકિર્દી આંતરદૃષ્ટિ મેળવવા તમારું રિઝ્યુમે અપલોડ કરો.",
    strengths: "શક્તિઓ",
    areasToImprove: "સુધારવાના ક્ષેત્રો",
    suggestedCourses: "સૂચવેલા કોર્સ:",
    skills: "કૌશલ્યો",
    jobRecommendations: "નોકરી ભલામણો",
    matchScore: "મેચ સ્કોર",
    requiredSkills: "જરૂરી કૌશલ્યો:",
    skillsToLearn: "શીખવાના કૌશલ્યો:",
    resumeImprovementTips: "રિઝ્યુમે સુધારણા ટિપ્સ",
  },
  kn: {
    home: "ಮುಖಪುಟ",
    uploadResume: "ರೆಸ್ಯೂಮೆ ಅಪ್‌ಲೋಡ್",
    careerInsights: "ವೃತ್ತಿ ಒಳನೋಟಗಳು",
    aiAdvisor: "AI ಸಲಹೆಗಾರ",
    configure: "ಕಾನ್ಫಿಗರ್",
    login: "ಲಾಗಿನ್",
    signOut: "ಸೈನ್ ಔಟ್",
    loginRequired: "ಲಾಗಿನ್ ಅಗತ್ಯ",
    loginRequiredDesc: "ಈ ವೈಶಿಷ್ಟ್ಯವನ್ನು ಪ್ರವೇಶಿಸಲು ಲಾಗಿನ್ ಮಾಡಿ.",
    loginSignUp: "ಲಾಗಿನ್ / ಸೈನ್ ಅಪ್",
    analyzeResume: "ನನ್ನ ರೆಸ್ಯೂಮೆ ವಿಶ್ಲೇಷಿಸಿ",
    analyzingResume: "ರೆಸ್ಯೂಮೆ ವಿಶ್ಲೇಷಣೆ ನಡೆಯುತ್ತಿದೆ...",
    uploadYourResume: "ನಿಮ್ಮ ರೆಸ್ಯೂಮೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    uploadDesc: "ನಮ್ಮ AI ನಿಮ್ಮ ರೆಸ್ಯೂಮೆ ವಿಶ್ಲೇಷಿಸುತ್ತದೆ.",
    dragDrop: "ನಿಮ್ಮ ರೆಸ್ಯೂಮೆ ಡ್ರ್ಯಾಗ್ ಮತ್ತು ಡ್ರಾಪ್ ಮಾಡಿ",
    browseFiles: "ಫೈಲ್‌ಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ",
    pasteResume: "ಅಥವಾ ನಿಮ್ಮ ರೆಸ್ಯೂಮೆ ಪಠ್ಯವನ್ನು ಅಂಟಿಸಿ:",
    pasteResumeDesc: "ನಿಮ್ಮ ಸಂಪೂರ್ಣ ರೆಸ್ಯೂಮೆ ವಿಷಯವನ್ನು ಇಲ್ಲಿ ಅಂಟಿಸಿ...",
    securityNotice: "ನಿಮ್ಮ ರೆಸ್ಯೂಮೆ ಡೇಟಾ ಸುರಕ್ಷಿತವಾಗಿ ಪ್ರಕ್ರಿಯೆಗೊಳ್ಳುತ್ತದೆ.",
    aiCareerAdvisor: "AI ವೃತ್ತಿ ಸಲಹೆಗಾರ",
    askAboutCareers: "ವೃತ್ತಿಗಳು, ಸಂದರ್ಶನಗಳ ಬಗ್ಗೆ ಕೇಳಿ...",
    welcomeBack: "ಮರಳಿ ಸ್ವಾಗತ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    signInContinue: "ನಿಮ್ಮ ವೃತ್ತಿ ಪ್ರಯಾಣವನ್ನು ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ",
    startExploring: "ನಿಮ್ಮ ವೃತ್ತಿ ಅವಕಾಶಗಳನ್ನು ಅನ್ವೇಷಿಸಲು ಪ್ರಾರಂಭಿಸಿ",
    fullName: "ಪೂರ್ಣ ಹೆಸರು",
    email: "ಇಮೇಲ್",
    password: "ಪಾಸ್‌ವರ್ಡ್",
    signIn: "ಸೈನ್ ಇನ್",
    dontHaveAccount: "ಖಾತೆ ಇಲ್ಲವೇ? ಸೈನ್ ಅಪ್ ಮಾಡಿ",
    alreadyHaveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ? ಸೈನ್ ಇನ್ ಮಾಡಿ",
    error: "ದೋಷ",
    fillAllFields: "ದಯವಿಟ್ಟು ಎಲ್ಲಾ ಕ್ಷೇತ್ರಗಳನ್ನು ಭರ್ತಿ ಮಾಡಿ.",
    enterName: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ಹೆಸರನ್ನು ನಮೂದಿಸಿ.",
    passwordLength: "ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಾಗಿರಬೇಕು.",
    invalidCredentials: "ಅಮಾನ್ಯ ಇಮೇಲ್ ಅಥವಾ ಪಾಸ್‌ವರ್ಡ್.",
    emailRegistered: "ಈ ಇಮೇಲ್ ಈಗಾಗಲೇ ನೋಂದಾಯಿಸಲಾಗಿದೆ.",
    confirmEmail: "ಲಾಗಿನ್ ಮಾಡುವ ಮೊದಲು ನಿಮ್ಮ ಇಮೇಲ್ ದೃಢೀಕರಿಸಿ.",
    genericError: "ದೋಷ ಸಂಭವಿಸಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    accountCreated: "ಖಾತೆ ರಚಿಸಲಾಗಿದೆ!",
    startUsing: "ಈಗ ನೀವು Career Explorer ಬಳಸಲು ಪ್ರಾರಂಭಿಸಬಹುದು.",
    loggedIn: "ನೀವು ಯಶಸ್ವಿಯಾಗಿ ಲಾಗಿನ್ ಆಗಿದ್ದೀರಿ.",
    chatWelcome: "ನಮಸ್ಕಾರ! ನಾನು CareerGuide AI, ನಿಮ್ಮ ವೈಯಕ್ತಿಕ ವೃತ್ತಿ ಸಲಹೆಗಾರ.",
    chatError: "ಕ್ಷಮಿಸಿ, ದೋಷ ಸಂಭವಿಸಿದೆ. ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.",
    aiPoweredCareer: "AI-ಚಾಲಿತ ವೃತ್ತಿ ಇಂಟೆಲಿಜೆನ್ಸ್",
    discoverPerfect: "ನಿಮ್ಮದನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ",
    perfectCareer: "ಪರಿಪೂರ್ಣ ವೃತ್ತಿ",
    pathWithAI: "AI ಯೊಂದಿಗೆ ಮಾರ್ಗ",
    heroDescription: "ನಿಮ್ಮ ರೆಸ್ಯೂಮೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ ಮತ್ತು ವೈಯಕ್ತೀಕೃತ ವೃತ್ತಿ ಶಿಫಾರಸುಗಳು, INR ನಲ್ಲಿ ಸಂಬಳ ಮಾಹಿತಿಯೊಂದಿಗೆ ಉದ್ಯೋಗ ಹೊಂದಾಣಿಕೆಗಳು ಮತ್ತು AI-ಚಾಲಿತ ಮಾರ್ಗದರ್ಶನ ಪಡೆಯಿರಿ.",
    chatWithAI: "AI ನೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ",
    securePrivate: "ಸುರಕ್ಷಿತ ಮತ್ತು ಖಾಸಗಿ",
    realTimeInsights: "ರಿಯಲ್-ಟೈಮ್ ಒಳನೋಟಗಳು",
    personalizedMatches: "ವೈಯಕ್ತೀಕೃತ ಹೊಂದಾಣಿಕೆಗಳು",
    smartResume: "ಸ್ಮಾರ್ಟ್ ರೆಸ್ಯೂಮೆ ವಿಶ್ಲೇಷಣೆ",
    smartResumeDesc: "AI ನಿಮ್ಮ ರೆಸ್ಯೂಮೆಯಿಂದ ಕೌಶಲ್ಯಗಳು, ಅನುಭವ ಮತ್ತು ಯೋಜನೆಗಳನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಹೊರತೆಗೆಯುತ್ತದೆ",
    jobMatching: "ಉದ್ಯೋಗ ಹೊಂದಾಣಿಕೆ",
    jobMatchingDesc: "ಹೊಂದಾಣಿಕೆ ಶೇಕಡಾವಾರು ಮತ್ತು ಸಂಬಳ ವ್ಯಾಪ್ತಿಗಳೊಂದಿಗೆ ವೈಯಕ್ತೀಕೃತ ಉದ್ಯೋಗ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ",
    careerGrowth: "ವೃತ್ತಿ ಬೆಳವಣಿಗೆ ಒಳನೋಟಗಳು",
    careerGrowthDesc: "ಕೌಶಲ್ಯ ಅಂತರಗಳನ್ನು ಕಂಡುಹಿಡಿಯಿರಿ ಮತ್ತು ಕ್ರಿಯಾತ್ಮಕ ಸುಧಾರಣೆ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ",
    howItWorks: "ಇದು ಹೇಗೆ",
    works: "ಕೆಲಸ ಮಾಡುತ್ತದೆ",
    howItWorksDesc: "ರೆಸ್ಯೂಮೆ ಅಪ್‌ಲೋಡ್‌ನಿಂದ ವೃತ್ತಿ ಯಶಸ್ಸಿನವರೆಗೆ — ನಮ್ಮ AI-ಚಾಲಿತ ವೇದಿಕೆ ಪ್ರತಿ ಹಂತದಲ್ಲೂ ನಿಮಗೆ ಮಾರ್ಗದರ್ಶನ ನೀಡುತ್ತದೆ.",
    uploadResumeStep: "ರೆಸ್ಯೂಮೆ ಅಪ್‌ಲೋಡ್",
    uploadResumeStepDesc: "PDF ಅಥವಾ ಪಠ್ಯ ಸ್ವರೂಪದಲ್ಲಿ ನಿಮ್ಮ ರೆಸ್ಯೂಮೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    aiAnalysis: "AI ವಿಶ್ಲೇಷಣೆ",
    aiAnalysisDesc: "ನಮ್ಮ AI ಕೌಶಲ್ಯಗಳು, ಅನುಭವ, ಯೋಜನೆಗಳನ್ನು ಹೊರತೆಗೆದು ನಿಮ್ಮ ವೃತ್ತಿಪರ ಪ್ರೊಫೈಲ್ ರಚಿಸುತ್ತದೆ.",
    jobMatchingStep: "ಉದ್ಯೋಗ ಹೊಂದಾಣಿಕೆ",
    jobMatchingStepDesc: "ಸಂಬಳ ವ್ಯಾಪ್ತಿಗಳೊಂದಿಗೆ ಅಗ್ರ ಭಾರತೀಯ ಕಂಪನಿಗಳಿಂದ ಸಂಬಂಧಿತ ಉದ್ಯೋಗ ಪಾತ್ರಗಳೊಂದಿಗೆ ಹೊಂದಿಕೆಯಾಗಿ.",
    careerInsightsStep: "ವೃತ್ತಿ ಒಳನೋಟಗಳು",
    careerInsightsStepDesc: "ಸಾಮರ್ಥ್ಯಗಳು, ದೌರ್ಬಲ್ಯಗಳು ಮತ್ತು ಸುಧಾರಣೆ ಕ್ಷೇತ್ರಗಳ ಬಗ್ಗೆ ವೈಯಕ್ತೀಕೃತ ಒಳನೋಟಗಳನ್ನು ಪಡೆಯಿರಿ.",
    aiAdvisorStep: "AI ಸಲಹೆಗಾರ",
    aiAdvisorStepDesc: "ಮಾರ್ಗದರ್ಶನ, ಸಂದರ್ಶನ ಸಲಹೆಗಳು ಮತ್ತು ಇನ್ನಷ್ಟಕ್ಕಾಗಿ ನಮ್ಮ AI ವೃತ್ತಿ ಸಲಹೆಗಾರರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ.",
    takeAction: "ಕ್ರಮ ತೆಗೆದುಕೊಳ್ಳಿ",
    takeActionDesc: "ಸುಧಾರಿತ ರೆಸ್ಯೂಮೆ ಮತ್ತು ಆತ್ಮವಿಶ್ವಾಸದೊಂದಿಗೆ ಹೊಂದಿಕೆಯಾದ ಉದ್ಯೋಗಗಳಿಗೆ ಅರ್ಜಿ ಸಲ್ಲಿಸಿ.",
    careerExplorer: "ವೃತ್ತಿ ಎಕ್ಸ್‌ಪ್ಲೋರರ್",
    footerDesc: "AI-ಚಾಲಿತ ಒಳನೋಟಗಳು, ವೈಯಕ್ತೀಕೃತ ಶಿಫಾರಸುಗಳು ಮತ್ತು ಸುರಕ್ಷಿತ ರೆಸ್ಯೂಮೆ ಪ್ರಕ್ರಿಯೆಯೊಂದಿಗೆ ನಿಮ್ಮ ವೃತ್ತಿ ಪ್ರಯಾಣವನ್ನು ಸಶಕ್ತಗೊಳಿಸುವುದು.",
    securityFirst: "ಭದ್ರತೆ ಮೊದಲು",
    endToEndEncryption: "ಎಂಡ್-ಟು-ಎಂಡ್ ಎನ್‌ಕ್ರಿಪ್ಶನ್",
    privacyProtected: "ಗೌಪ್ಯತೆ ರಕ್ಷಿಸಲಾಗಿದೆ",
    quickLinks: "ತ್ವರಿತ ಲಿಂಕ್‌ಗಳು",
    madeWith: "ತಯಾರಿಸಲಾಗಿದೆ",
    forCareer: "ನಿಮ್ಮ ವೃತ್ತಿ ಯಶಸ್ಸಿಗಾಗಿ",
    allRightsReserved: "ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.",
    yourCareer: "ನಿಮ್ಮ ವೃತ್ತಿ",
    insights: "ಒಳನೋಟಗಳು",
    noResumeYet: "ಇನ್ನೂ ರೆಸ್ಯೂಮೆ ವಿಶ್ಲೇಷಿಸಲಾಗಿಲ್ಲ",
    uploadToGetInsights: "ವೈಯಕ್ತೀಕೃತ ವೃತ್ತಿ ಒಳನೋಟಗಳನ್ನು ಪಡೆಯಲು ನಿಮ್ಮ ರೆಸ್ಯೂಮೆ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    strengths: "ಸಾಮರ್ಥ್ಯಗಳು",
    areasToImprove: "ಸುಧಾರಿಸಬೇಕಾದ ಕ್ಷೇತ್ರಗಳು",
    suggestedCourses: "ಸೂಚಿಸಿದ ಕೋರ್ಸ್‌ಗಳು:",
    skills: "ಕೌಶಲ್ಯಗಳು",
    jobRecommendations: "ಉದ್ಯೋಗ ಶಿಫಾರಸುಗಳು",
    matchScore: "ಹೊಂದಾಣಿಕೆ ಸ್ಕೋರ್",
    requiredSkills: "ಅಗತ್ಯ ಕೌಶಲ್ಯಗಳು:",
    skillsToLearn: "ಕಲಿಯಬೇಕಾದ ಕೌಶಲ್ಯಗಳು:",
    resumeImprovementTips: "ರೆಸ್ಯೂಮೆ ಸುಧಾರಣೆ ಸಲಹೆಗಳು",
  },
  ml: {
    home: "ഹോം",
    uploadResume: "റെസ്യൂമെ അപ്‌ലോഡ്",
    careerInsights: "കരിയർ ഇൻസൈറ്റ്സ്",
    aiAdvisor: "AI ഉപദേശകൻ",
    configure: "കോൺഫിഗർ",
    login: "ലോഗിൻ",
    signOut: "സൈൻ ഔട്ട്",
    loginRequired: "ലോഗിൻ ആവശ്യമാണ്",
    loginRequiredDesc: "ഈ ഫീച്ചർ ആക്‌സസ് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക.",
    loginSignUp: "ലോഗിൻ / സൈൻ അപ്",
    analyzeResume: "എന്റെ റെസ്യൂമെ വിശകലനം ചെയ്യുക",
    analyzingResume: "റെസ്യൂമെ വിശകലനം ചെയ്യുന്നു...",
    uploadYourResume: "നിങ്ങളുടെ റെസ്യൂമെ അപ്‌ലോഡ് ചെയ്യുക",
    uploadDesc: "ഞങ്ങളുടെ AI നിങ്ങളുടെ റെസ്യൂമെ വിശകലനം ചെയ്യും.",
    dragDrop: "നിങ്ങളുടെ റെസ്യൂമെ ഡ്രാഗ് & ഡ്രോപ്പ് ചെയ്യുക",
    browseFiles: "ഫയലുകൾ ബ്രൗസ് ചെയ്യുക",
    pasteResume: "അല്ലെങ്കിൽ നിങ്ങളുടെ റെസ്യൂമെ ടെക്സ്റ്റ് പേസ്റ്റ് ചെയ്യുക:",
    pasteResumeDesc: "നിങ്ങളുടെ പൂർണ്ണ റെസ്യൂമെ ഉള്ളടക്കം ഇവിടെ പേസ്റ്റ് ചെയ്യുക...",
    securityNotice: "നിങ്ങളുടെ റെസ്യൂമെ ഡാറ്റ സുരക്ഷിതമായി പ്രോസസ്സ് ചെയ്യുന്നു.",
    aiCareerAdvisor: "AI കരിയർ ഉപദേശകൻ",
    askAboutCareers: "കരിയറുകൾ, അഭിമുഖങ്ങൾ എന്നിവയെക്കുറിച്ച് ചോദിക്കുക...",
    welcomeBack: "തിരികെ സ്വാഗതം",
    createAccount: "അക്കൗണ്ട് സൃഷ്ടിക്കുക",
    signInContinue: "നിങ്ങളുടെ കരിയർ യാത്ര തുടരാൻ സൈൻ ഇൻ ചെയ്യുക",
    startExploring: "നിങ്ങളുടെ കരിയർ സാധ്യതകൾ കണ്ടെത്താൻ തുടങ്ങുക",
    fullName: "മുഴുവൻ പേര്",
    email: "ഇമെയിൽ",
    password: "പാസ്‌വേഡ്",
    signIn: "സൈൻ ഇൻ",
    dontHaveAccount: "അക്കൗണ്ട് ഇല്ലേ? സൈൻ അപ്പ് ചെയ്യുക",
    alreadyHaveAccount: "ഇതിനകം അക്കൗണ്ട് ഉണ്ടോ? സൈൻ ഇൻ ചെയ്യുക",
    error: "പിശക്",
    fillAllFields: "എല്ലാ ഫീൽഡുകളും പൂരിപ്പിക്കുക.",
    enterName: "നിങ്ങളുടെ പേര് നൽകുക.",
    passwordLength: "പാസ്‌വേഡ് കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ ആയിരിക്കണം.",
    invalidCredentials: "അസാധുവായ ഇമെയിൽ അല്ലെങ്കിൽ പാസ്‌വേഡ്.",
    emailRegistered: "ഈ ഇമെയിൽ ഇതിനകം രജിസ്റ്റർ ചെയ്തിട്ടുണ്ട്.",
    confirmEmail: "ലോഗിൻ ചെയ്യുന്നതിന് മുമ്പ് നിങ്ങളുടെ ഇമെയിൽ സ്ഥിരീകരിക്കുക.",
    genericError: "ഒരു പിശക് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കുക.",
    accountCreated: "അക്കൗണ്ട് സൃഷ്ടിച്ചു!",
    startUsing: "ഇപ്പോൾ നിങ്ങൾക്ക് Career Explorer ഉപയോഗിക്കാൻ തുടങ്ങാം.",
    loggedIn: "നിങ്ങൾ വിജയകരമായി ലോഗിൻ ചെയ്തു.",
    chatWelcome: "ഹലോ! ഞാൻ CareerGuide AI ആണ്, നിങ്ങളുടെ വ്യക്തിഗത കരിയർ ഉപദേശകൻ.",
    chatError: "ക്ഷമിക്കണം, ഒരു പിശക് സംഭവിച്ചു. വീണ്ടും ശ്രമിക്കുക.",
    aiPoweredCareer: "AI-പ്രവർത്തിത കരിയർ ഇന്റലിജൻസ്",
    discoverPerfect: "നിങ്ങളുടെ കണ്ടെത്തുക",
    perfectCareer: "മികച്ച കരിയർ",
    pathWithAI: "AI യുമായി പാത",
    heroDescription: "നിങ്ങളുടെ റെസ്യൂമെ അപ്‌ലോഡ് ചെയ്ത് വ്യക്തിഗതമാക്കിയ കരിയർ ശുപാർശകൾ, INR ൽ ശമ്പള വിവരങ്ങളുള്ള ജോലി പൊരുത്തങ്ങൾ, AI-പ്രവർത്തിത മാർഗ്ഗനിർദ്ദേശം എന്നിവ നേടുക.",
    chatWithAI: "AI യുമായി ചാറ്റ് ചെയ്യുക",
    securePrivate: "സുരക്ഷിതവും സ്വകാര്യവും",
    realTimeInsights: "റിയൽ-ടൈം ഇൻസൈറ്റ്സ്",
    personalizedMatches: "വ്യക്തിഗതമാക്കിയ പൊരുത്തങ്ങൾ",
    smartResume: "സ്മാർട്ട് റെസ്യൂമെ വിശകലനം",
    smartResumeDesc: "AI നിങ്ങളുടെ റെസ്യൂമെയിൽ നിന്ന് വൈദഗ്ധ്യങ്ങൾ, അനുഭവം, പ്രോജക്ടുകൾ എന്നിവ സ്വയമേവ എക്സ്ട്രാക്ട് ചെയ്യുന്നു",
    jobMatching: "ജോലി പൊരുത്തം",
    jobMatchingDesc: "പൊരുത്ത ശതമാനവും ശമ്പള ശ്രേണിയും ഉള്ള വ്യക്തിഗതമാക്കിയ ജോലി ശുപാർശകൾ നേടുക",
    careerGrowth: "കരിയർ വളർച്ച ഇൻസൈറ്റ്സ്",
    careerGrowthDesc: "വൈദഗ്ധ്യ വിടവുകൾ കണ്ടെത്തുകയും പ്രവർത്തനക്ഷമമായ മെച്ചപ്പെടുത്തൽ നിർദ്ദേശങ്ങൾ നേടുകയും ചെയ്യുക",
    howItWorks: "ഇത് എങ്ങനെ",
    works: "പ്രവർത്തിക്കുന്നു",
    howItWorksDesc: "റെസ്യൂമെ അപ്‌ലോഡ് മുതൽ കരിയർ വിജയം വരെ — ഞങ്ങളുടെ AI-പ്രവർത്തിത പ്ലാറ്റ്‌ഫോം എല്ലാ ഘട്ടത്തിലും നിങ്ങളെ നയിക്കുന്നു.",
    uploadResumeStep: "റെസ്യൂമെ അപ്‌ലോഡ്",
    uploadResumeStepDesc: "PDF അല്ലെങ്കിൽ ടെക്സ്റ്റ് ഫോർമാറ്റിൽ നിങ്ങളുടെ റെസ്യൂമെ അപ്‌ലോഡ് ചെയ്യുക.",
    aiAnalysis: "AI വിശകലനം",
    aiAnalysisDesc: "ഞങ്ങളുടെ AI വൈദഗ്ധ്യങ്ങൾ, അനുഭവം, പ്രോജക്ടുകൾ എക്സ്ട്രാക്ട് ചെയ്ത് നിങ്ങളുടെ പ്രൊഫഷണൽ പ്രൊഫൈൽ സൃഷ്ടിക്കുന്നു.",
    jobMatchingStep: "ജോലി പൊരുത്തം",
    jobMatchingStepDesc: "ശമ്പള ശ്രേണികളുള്ള മുൻനിര ഇന്ത്യൻ കമ്പനികളിൽ നിന്നുള്ള പ്രസക്തമായ ജോലി റോളുകളുമായി പൊരുത്തപ്പെടുക.",
    careerInsightsStep: "കരിയർ ഇൻസൈറ്റ്സ്",
    careerInsightsStepDesc: "ശക്തികൾ, ബലഹീനതകൾ, മെച്ചപ്പെടുത്തൽ മേഖലകൾ എന്നിവയെക്കുറിച്ച് വ്യക്തിഗതമാക്കിയ ഇൻസൈറ്റ്സ് നേടുക.",
    aiAdvisorStep: "AI ഉപദേശകൻ",
    aiAdvisorStepDesc: "മാർഗ്ഗനിർദ്ദേശം, അഭിമുഖ ടിപ്പുകൾ എന്നിവയ്ക്കായി ഞങ്ങളുടെ AI കരിയർ ഉപദേശകനുമായി ചാറ്റ് ചെയ്യുക.",
    takeAction: "നടപടി എടുക്കുക",
    takeActionDesc: "മെച്ചപ്പെടുത്തിയ റെസ്യൂമെയും ആത്മവിശ്വാസവുമായി പൊരുത്തപ്പെട്ട ജോലികൾക്ക് അപേക്ഷിക്കുക.",
    careerExplorer: "കരിയർ എക്സ്‌പ്ലോറർ",
    footerDesc: "AI-പ്രവർത്തിത ഇൻസൈറ്റ്സ്, വ്യക്തിഗതമാക്കിയ ശുപാർശകൾ, സുരക്ഷിത റെസ്യൂമെ പ്രോസസ്സിംഗ് എന്നിവയിലൂടെ നിങ്ങളുടെ കരിയർ യാത്രയെ ശക്തിപ്പെടുത്തുന്നു.",
    securityFirst: "സുരക്ഷ ആദ്യം",
    endToEndEncryption: "എൻഡ്-ടു-എൻഡ് എൻക്രിപ്ഷൻ",
    privacyProtected: "സ്വകാര്യത സംരക്ഷിതം",
    quickLinks: "ദ്രുത ലിങ്കുകൾ",
    madeWith: "നിർമ്മിച്ചത്",
    forCareer: "നിങ്ങളുടെ കരിയർ വിജയത്തിനായി",
    allRightsReserved: "എല്ലാ അവകാശങ്ങളും സംരക്ഷിതം.",
    yourCareer: "നിങ്ങളുടെ കരിയർ",
    insights: "ഇൻസൈറ്റ്സ്",
    noResumeYet: "ഇതുവരെ റെസ്യൂമെ വിശകലനം ചെയ്തിട്ടില്ല",
    uploadToGetInsights: "വ്യക്തിഗതമാക്കിയ കരിയർ ഇൻസൈറ്റ്സ് നേടാൻ നിങ്ങളുടെ റെസ്യൂമെ അപ്‌ലോഡ് ചെയ്യുക.",
    strengths: "ശക്തികൾ",
    areasToImprove: "മെച്ചപ്പെടുത്തേണ്ട മേഖലകൾ",
    suggestedCourses: "നിർദ്ദേശിച്ച കോഴ്‌സുകൾ:",
    skills: "വൈദഗ്ധ്യങ്ങൾ",
    jobRecommendations: "ജോലി ശുപാർശകൾ",
    matchScore: "പൊരുത്ത സ്‌കോർ",
    requiredSkills: "ആവശ്യമായ വൈദഗ്ധ്യങ്ങൾ:",
    skillsToLearn: "പഠിക്കേണ്ട വൈദഗ്ധ്യങ്ങൾ:",
    resumeImprovementTips: "റെസ്യൂമെ മെച്ചപ്പെടുത്തൽ ടിപ്പുകൾ",
  },
  pa: {
    home: "ਹੋਮ",
    uploadResume: "ਰਿਜ਼ਿਊਮੇ ਅੱਪਲੋਡ ਕਰੋ",
    careerInsights: "ਕਰੀਅਰ ਇਨਸਾਈਟਸ",
    aiAdvisor: "AI ਸਲਾਹਕਾਰ",
    configure: "ਕੌਂਫਿਗਰ",
    login: "ਲੌਗਇਨ",
    signOut: "ਸਾਈਨ ਆਊਟ",
    loginRequired: "ਲੌਗਇਨ ਜ਼ਰੂਰੀ ਹੈ",
    loginRequiredDesc: "ਇਸ ਵਿਸ਼ੇਸ਼ਤਾ ਤੱਕ ਪਹੁੰਚ ਲਈ ਲੌਗਇਨ ਕਰੋ।",
    loginSignUp: "ਲੌਗਇਨ / ਸਾਈਨ ਅੱਪ",
    analyzeResume: "ਮੇਰਾ ਰਿਜ਼ਿਊਮੇ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ",
    analyzingResume: "ਰਿਜ਼ਿਊਮੇ ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...",
    uploadYourResume: "ਆਪਣਾ ਰਿਜ਼ਿਊਮੇ ਅੱਪਲੋਡ ਕਰੋ",
    uploadDesc: "ਸਾਡਾ AI ਤੁਹਾਡੇ ਰਿਜ਼ਿਊਮੇ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੇਗਾ।",
    dragDrop: "ਆਪਣਾ ਰਿਜ਼ਿਊਮੇ ਡ੍ਰੈਗ ਅਤੇ ਡ੍ਰਾਪ ਕਰੋ",
    browseFiles: "ਫ਼ਾਈਲਾਂ ਬ੍ਰਾਊਜ਼ ਕਰੋ",
    pasteResume: "ਜਾਂ ਆਪਣਾ ਰਿਜ਼ਿਊਮੇ ਟੈਕਸਟ ਪੇਸਟ ਕਰੋ:",
    pasteResumeDesc: "ਆਪਣੀ ਪੂਰੀ ਰਿਜ਼ਿਊਮੇ ਸਮੱਗਰੀ ਇੱਥੇ ਪੇਸਟ ਕਰੋ...",
    securityNotice: "ਤੁਹਾਡਾ ਰਿਜ਼ਿਊਮੇ ਡਾਟਾ ਸੁਰੱਖਿਅਤ ਢੰਗ ਨਾਲ ਪ੍ਰੋਸੈਸ ਕੀਤਾ ਜਾਂਦਾ ਹੈ।",
    aiCareerAdvisor: "AI ਕਰੀਅਰ ਸਲਾਹਕਾਰ",
    askAboutCareers: "ਕਰੀਅਰ, ਇੰਟਰਵਿਊ ਬਾਰੇ ਪੁੱਛੋ...",
    welcomeBack: "ਵਾਪਸੀ ਤੇ ਸੁਆਗਤ ਹੈ",
    createAccount: "ਖਾਤਾ ਬਣਾਓ",
    signInContinue: "ਆਪਣੀ ਕਰੀਅਰ ਯਾਤਰਾ ਜਾਰੀ ਰੱਖਣ ਲਈ ਸਾਈਨ ਇਨ ਕਰੋ",
    startExploring: "ਆਪਣੀਆਂ ਕਰੀਅਰ ਸੰਭਾਵਨਾਵਾਂ ਦੀ ਖੋਜ ਸ਼ੁਰੂ ਕਰੋ",
    fullName: "ਪੂਰਾ ਨਾਮ",
    email: "ਈਮੇਲ",
    password: "ਪਾਸਵਰਡ",
    signIn: "ਸਾਈਨ ਇਨ",
    dontHaveAccount: "ਖਾਤਾ ਨਹੀਂ ਹੈ? ਸਾਈਨ ਅੱਪ ਕਰੋ",
    alreadyHaveAccount: "ਪਹਿਲਾਂ ਤੋਂ ਖਾਤਾ ਹੈ? ਸਾਈਨ ਇਨ ਕਰੋ",
    error: "ਗਲਤੀ",
    fillAllFields: "ਕਿਰਪਾ ਕਰਕੇ ਸਾਰੇ ਖੇਤਰ ਭਰੋ।",
    enterName: "ਕਿਰਪਾ ਕਰਕੇ ਆਪਣਾ ਨਾਮ ਦਾਖਲ ਕਰੋ।",
    passwordLength: "ਪਾਸਵਰਡ ਘੱਟੋ-ਘੱਟ 6 ਅੱਖਰ ਹੋਣਾ ਚਾਹੀਦਾ ਹੈ।",
    invalidCredentials: "ਅਵੈਧ ਈਮੇਲ ਜਾਂ ਪਾਸਵਰਡ।",
    emailRegistered: "ਇਹ ਈਮੇਲ ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੈ।",
    confirmEmail: "ਲੌਗਇਨ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਆਪਣੀ ਈਮੇਲ ਦੀ ਪੁਸ਼ਟੀ ਕਰੋ।",
    genericError: "ਇੱਕ ਗਲਤੀ ਹੋਈ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    accountCreated: "ਖਾਤਾ ਬਣਾਇਆ ਗਿਆ!",
    startUsing: "ਹੁਣ ਤੁਸੀਂ Career Explorer ਵਰਤਣਾ ਸ਼ੁਰੂ ਕਰ ਸਕਦੇ ਹੋ।",
    loggedIn: "ਤੁਸੀਂ ਸਫਲਤਾਪੂਰਵਕ ਲੌਗਇਨ ਹੋ ਗਏ।",
    chatWelcome: "ਸਤ ਸ੍ਰੀ ਅਕਾਲ! ਮੈਂ CareerGuide AI ਹਾਂ, ਤੁਹਾਡਾ ਨਿੱਜੀ ਕਰੀਅਰ ਸਲਾਹਕਾਰ।",
    chatError: "ਮਾਫ਼ ਕਰਨਾ, ਇੱਕ ਗਲਤੀ ਹੋਈ। ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    aiPoweredCareer: "AI-ਸੰਚਾਲਿਤ ਕਰੀਅਰ ਇੰਟੈਲੀਜੈਂਸ",
    discoverPerfect: "ਆਪਣਾ ਲੱਭੋ",
    perfectCareer: "ਸੰਪੂਰਨ ਕਰੀਅਰ",
    pathWithAI: "AI ਨਾਲ ਰਸਤਾ",
    heroDescription: "ਆਪਣਾ ਰਿਜ਼ਿਊਮੇ ਅੱਪਲੋਡ ਕਰੋ ਅਤੇ ਨਿੱਜੀ ਕਰੀਅਰ ਸਿਫਾਰਸ਼ਾਂ, INR ਵਿੱਚ ਤਨਖਾਹ ਜਾਣਕਾਰੀ ਨਾਲ ਨੌਕਰੀ ਮੈਚ ਅਤੇ AI-ਸੰਚਾਲਿਤ ਮਾਰਗਦਰਸ਼ਨ ਪ੍ਰਾਪਤ ਕਰੋ।",
    chatWithAI: "AI ਨਾਲ ਚੈਟ ਕਰੋ",
    securePrivate: "ਸੁਰੱਖਿਅਤ ਅਤੇ ਨਿੱਜੀ",
    realTimeInsights: "ਰੀਅਲ-ਟਾਈਮ ਇਨਸਾਈਟਸ",
    personalizedMatches: "ਨਿੱਜੀ ਮੈਚ",
    smartResume: "ਸਮਾਰਟ ਰਿਜ਼ਿਊਮੇ ਵਿਸ਼ਲੇਸ਼ਣ",
    smartResumeDesc: "AI ਤੁਹਾਡੇ ਰਿਜ਼ਿਊਮੇ ਤੋਂ ਹੁਨਰ, ਤਜਰਬਾ ਅਤੇ ਪ੍ਰੋਜੈਕਟ ਆਪਣੇ ਆਪ ਕੱਢਦਾ ਹੈ",
    jobMatching: "ਨੌਕਰੀ ਮੈਚਿੰਗ",
    jobMatchingDesc: "ਮੈਚ ਪ੍ਰਤੀਸ਼ਤ ਅਤੇ ਤਨਖਾਹ ਰੇਂਜ ਨਾਲ ਨਿੱਜੀ ਨੌਕਰੀ ਸਿਫਾਰਸ਼ਾਂ ਪ੍ਰਾਪਤ ਕਰੋ",
    careerGrowth: "ਕਰੀਅਰ ਵਾਧਾ ਇਨਸਾਈਟਸ",
    careerGrowthDesc: "ਹੁਨਰ ਦੀਆਂ ਕਮੀਆਂ ਲੱਭੋ ਅਤੇ ਕਾਰਵਾਈਯੋਗ ਸੁਧਾਰ ਸੁਝਾਅ ਪ੍ਰਾਪਤ ਕਰੋ",
    howItWorks: "ਇਹ ਕਿਵੇਂ",
    works: "ਕੰਮ ਕਰਦਾ ਹੈ",
    howItWorksDesc: "ਰਿਜ਼ਿਊਮੇ ਅੱਪਲੋਡ ਤੋਂ ਕਰੀਅਰ ਸਫਲਤਾ ਤੱਕ — ਸਾਡਾ AI-ਸੰਚਾਲਿਤ ਪਲੇਟਫਾਰਮ ਹਰ ਕਦਮ ਤੇ ਤੁਹਾਡੀ ਅਗਵਾਈ ਕਰਦਾ ਹੈ।",
    uploadResumeStep: "ਰਿਜ਼ਿਊਮੇ ਅੱਪਲੋਡ ਕਰੋ",
    uploadResumeStepDesc: "PDF ਜਾਂ ਟੈਕਸਟ ਫਾਰਮੈਟ ਵਿੱਚ ਆਪਣਾ ਰਿਜ਼ਿਊਮੇ ਅੱਪਲੋਡ ਕਰੋ।",
    aiAnalysis: "AI ਵਿਸ਼ਲੇਸ਼ਣ",
    aiAnalysisDesc: "ਸਾਡਾ AI ਹੁਨਰ, ਤਜਰਬਾ, ਪ੍ਰੋਜੈਕਟ ਕੱਢਦਾ ਹੈ ਅਤੇ ਤੁਹਾਡੀ ਪੇਸ਼ੇਵਰ ਪ੍ਰੋਫਾਈਲ ਬਣਾਉਂਦਾ ਹੈ।",
    jobMatchingStep: "ਨੌਕਰੀ ਮੈਚਿੰਗ",
    jobMatchingStepDesc: "ਤਨਖਾਹ ਰੇਂਜ ਨਾਲ ਮੋਹਰੀ ਭਾਰਤੀ ਕੰਪਨੀਆਂ ਤੋਂ ਸੰਬੰਧਿਤ ਨੌਕਰੀ ਭੂਮਿਕਾਵਾਂ ਨਾਲ ਮੈਚ ਕਰੋ।",
    careerInsightsStep: "ਕਰੀਅਰ ਇਨਸਾਈਟਸ",
    careerInsightsStepDesc: "ਤਾਕਤਾਂ, ਕਮਜ਼ੋਰੀਆਂ ਅਤੇ ਸੁਧਾਰ ਖੇਤਰਾਂ ਤੇ ਨਿੱਜੀ ਇਨਸਾਈਟਸ ਪ੍ਰਾਪਤ ਕਰੋ।",
    aiAdvisorStep: "AI ਸਲਾਹਕਾਰ",
    aiAdvisorStepDesc: "ਮਾਰਗਦਰਸ਼ਨ, ਇੰਟਰਵਿਊ ਟਿਪਸ ਅਤੇ ਹੋਰ ਲਈ ਸਾਡੇ AI ਕਰੀਅਰ ਸਲਾਹਕਾਰ ਨਾਲ ਚੈਟ ਕਰੋ।",
    takeAction: "ਕਾਰਵਾਈ ਕਰੋ",
    takeActionDesc: "ਸੁਧਾਰੇ ਰਿਜ਼ਿਊਮੇ ਅਤੇ ਆਤਮਵਿਸ਼ਵਾਸ ਨਾਲ ਮੈਚ ਹੋਈਆਂ ਨੌਕਰੀਆਂ ਲਈ ਅਰਜ਼ੀ ਦਿਓ।",
    careerExplorer: "ਕਰੀਅਰ ਐਕਸਪਲੋਰਰ",
    footerDesc: "AI-ਸੰਚਾਲਿਤ ਇਨਸਾਈਟਸ, ਨਿੱਜੀ ਸਿਫਾਰਸ਼ਾਂ ਅਤੇ ਸੁਰੱਖਿਅਤ ਰਿਜ਼ਿਊਮੇ ਪ੍ਰੋਸੈਸਿੰਗ ਨਾਲ ਤੁਹਾਡੀ ਕਰੀਅਰ ਯਾਤਰਾ ਨੂੰ ਸ਼ਕਤੀ ਦੇਣਾ।",
    securityFirst: "ਸੁਰੱਖਿਆ ਪਹਿਲਾਂ",
    endToEndEncryption: "ਐਂਡ-ਟੂ-ਐਂਡ ਐਨਕ੍ਰਿਪਸ਼ਨ",
    privacyProtected: "ਗੋਪਨੀਯਤਾ ਸੁਰੱਖਿਅਤ",
    quickLinks: "ਤੇਜ਼ ਲਿੰਕ",
    madeWith: "ਬਣਾਇਆ ਗਿਆ",
    forCareer: "ਤੁਹਾਡੀ ਕਰੀਅਰ ਸਫਲਤਾ ਲਈ",
    allRightsReserved: "ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।",
    yourCareer: "ਤੁਹਾਡਾ ਕਰੀਅਰ",
    insights: "ਇਨਸਾਈਟਸ",
    noResumeYet: "ਅਜੇ ਤੱਕ ਕੋਈ ਰਿਜ਼ਿਊਮੇ ਵਿਸ਼ਲੇਸ਼ਣ ਨਹੀਂ ਕੀਤਾ",
    uploadToGetInsights: "ਨਿੱਜੀ ਕਰੀਅਰ ਇਨਸਾਈਟਸ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਆਪਣਾ ਰਿਜ਼ਿਊਮੇ ਅੱਪਲੋਡ ਕਰੋ।",
    strengths: "ਤਾਕਤਾਂ",
    areasToImprove: "ਸੁਧਾਰ ਦੇ ਖੇਤਰ",
    suggestedCourses: "ਸੁਝਾਏ ਗਏ ਕੋਰਸ:",
    skills: "ਹੁਨਰ",
    jobRecommendations: "ਨੌਕਰੀ ਸਿਫਾਰਸ਼ਾਂ",
    matchScore: "ਮੈਚ ਸਕੋਰ",
    requiredSkills: "ਲੋੜੀਂਦੇ ਹੁਨਰ:",
    skillsToLearn: "ਸਿੱਖਣ ਲਈ ਹੁਨਰ:",
    resumeImprovementTips: "ਰਿਜ਼ਿਊਮੇ ਸੁਧਾਰ ਟਿਪਸ",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved as Language) || "en";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
